const people = [
  {
    name: 'Jeff Bezos',
    age: 57,
    currency: '$',
    finance: 193.1,
    source: `Amazon`,
    country: 'United States',
  },
  {
    name: 'Elon Musk',
    age: 50,
    currency: '$',
    finance: 180.2,
    source: `Tesla, SpaceX`,
    country: 'United States',
  },
  {
    name: 'Bernard Arnault',
    age: 72,
    currency: '$',
    finance: 148.9,
    source: `LVMH`,
    country: 'France',
  },
  {
    name: 'Bill Gates',
    age: 66,
    currency: '$',
    finance: 121.5,
    source: `Microsoft`,
    country: 'United States',
  },
  {
    name: 'Mark Zuckerberg',
    age: 37,
    currency: '$',
    finance: 96.5,
    source: `Facebook`,
    country: 'United States',
  },
  {
    name: 'Zhong Shanshan',
    age: 67,
    currency: '$',
    finance: 91.3,
    source: `beverages, pharmaceuticals`,
    country: 'China',
  },
  {
    name: 'Warren Buffet',
    age: 91,
    currency: '$',
    finance: 87.2,
    source: `Berkshire Hathaway`,
    country: 'United States',
  },
  {
    name: 'Larry Ellison',
    age: 77,
    currency: '$',
    finance: 87.1,
    source: `software`,
    country: 'United States',
  },
  {
    name: 'Larry Page',
    age: 48,
    currency: '$',
    finance: 83.4,
    source: `Google`,
    country: 'United States',
  },
  {
    name: 'Sergey Brin',
    age: 48,
    currency: '$',
    finance: 81.0,
    source: `Google`,
    country: 'United States',
  },
  {
    name: 'Steve Ballmer',
    age: 65,
    currency: '$',
    finance: 80.4,
    source: `Microsoft`,
    country: 'United States',
  },
  {
    name: 'Mukesh Ambani',
    age: 64,
    currency: '$',
    finance: 73.3,
    source: `diversified`,
    country: 'India',
  },
  {
    name: 'Amancio Ortega',
    age: 68,
    currency: '$',
    finance: 71.1,
    source: `L'Oreal`,
    country: 'France',
  },
  {
    name: 'Francoise Bettencourt Meyers',
    age: 85,
    currency: '$',
    finance: 70.5,
    source: `Zara`,
    country: 'Spain',
  },
  {
    name: 'Ma Huateng',
    age: 50,
    currency: '$',
    finance: 68.9,
    source: `internet media`,
    country: 'China',
  },
  {
    name: 'Alice Walton',
    age: 72,
    currency: '$',
    finance: 65.7,
    source: `Walmart`,
    country: 'United States',
  },
  {
    name: 'Jim Walton',
    age: 73,
    currency: '$',
    finance: 65.5,
    source: `Walmart`,
    country: 'United States',
  },
  {
    name: 'Rob Walton',
    age: 77,
    currency: '$',
    finance: 65.2,
    source: `Walmart`,
    country: 'United States',
  },
  {
    name: 'Jack Ma',
    age: 57,
    currency: '$',
    finance: 61.8,
    source: `e-commerce`,
    country: 'China',
  },
  {
    name: 'Zheng Huang',
    age: 41,
    currency: '$',
    finance: 60.3,
    source: `e-commerce`,
    country: 'China',
  },
]

export default people